[tool.poetry]
name = "credit-score-prediction"
version = "0.1.0"
description = "An end-to-end example of how to apply software engineering practices for ML training, testing and deployment"
authors = ["David Tan <davidtan@thoughtworks.com>"]
packages = [{include = "training", from = "src"}]

[tool.poetry.dependencies]
pandas = "1.5.1"
scikit-learn = "1.1.3"
fastapi = "0.85.2"
pydantic = "1.10.2"
uvicorn = "0.20.0"
python = "^3.9"

[tool.poetry.dev-dependencies]
jupyter = "1.0.0"
black = "22.10.0"
pylint = "2.15.5"
precisely = "^0.1.9"
pytest = "^7.2.0"
requests = "^2.28.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"